name: docs

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - run: python -m pip install --upgrade pip
            - run: pip install mkdocs-gitbook mkdocstrings mkdocs-git-revision-date-plugin mkdocs-jupyter ipykernel
            - run: cp README.md docs/index.md
            - run: mkdocs gh-deploy --force
